### ISSUE TITLE
Wonky camera angles when viewing the panel for Zelda: Ocarina of Time 3D

### ISSUE THREAD

**Issue by AromaKitsune** [DBBDX/Puzzle-Swap-SpotPass-BOSS#1]
When viewing the panel for Zelda: Ocarina of Time 3D and moving the Circle Pad around, the camera angles are wonky and it can pan further than normal.

Here's the comparison between the normal (left) and wonky (right) camera behaviours, while the Circle Pad is moved to the left.

- Left: The camera slightly pans to the left.
- Right: The camera pans further to the right. You can see that the terrain ahead isn't loaded before it appears, because the camera isn't supposed to look that way.

I confirmed that the wonky camera behaviour occurs on a real 3DS, so it's not a Citra bug lol.

![2024-07-21_22-36-33](https://github.com/user-attachments/assets/709aeeed-efe4-43f9-b761-58a909775566)

See this video of the bug: https://youtu.be/-xuCKdeODBE

This bug is present in the 27MB SpotPass file for all regions, the file responsible for this panel's camera movement is `7_settings.bin`.

I compared the two `7_settings.bin` files from:

- the original BOSS files from [Internet Archive](https://archive.org/details/StreetPass-Puzzle-Swap-Data-Files)
- and your custom BOSS files

in Notepad++ and found out that the max camera angle values were increased from `15` to `95`. Not sure how it ended up changing those values in this file.

![2024-07-21_22-04-43_notepad++](https://github.com/user-attachments/assets/f15acb06-bef4-4201-beba-c44a77b04334)

Here's the `7_settings.bin` file extracted from the original BOSS file on Internet Archive so you can fix it:

[7_settings.zip](https://github.com/user-attachments/files/16326162/7_settings.zip)

**Comment by DBBDX** [comment]
Thanks for the help! The files were fixed in the latest update https://github.com/DBBDX/Puzzle-Swap-SpotPass-BOSS/releases/tag/BOSS.
If you encounter any other problem, let me know
